name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.4'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.3

      - name: Run CI checks
        run: make ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.33.0
    timeout-minutes: 10
    steps:

      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run lint
        run: make lint

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: actions/checkout@v2.3.3
      - name: Codespell test
        uses: codespell-project/actions-codespell@master
        with:
          skip: ./vendor,./.git,./lokoctl,*.png,./assets/charts/components/cert-manager,./assets/charts/components/external-dns,./assets/charts/components/rook,./assets/charts/components/prometheus-operator,./assets/charts/components/velero,./assets/charts/components/cluster-autoscaler,./assets/charts/components/contour/crds,./assets/charts/components/openebs-operator/README.md,./assets/charts/control-plane/calico/crds,./docs/images/lokomotive-example.gif,./assets/terraform-modules/tinkerbell-sandbox/assets/setup.sh,./assets/charts/control-plane/prometheus-operator-crds/templates
          ignore_words_file: './.codespell.ignorewords'
          check_filenames: true
          check_hidden: true
